name: examprep
description: Exam preparation app for entrance exams with learning and simulation modes.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  uuid: ^4.4.0

  # UI
  cupertino_icons: ^1.0.6

assets:
  - assets/i18n/
  - assets/questions/

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/en.json
    - assets/i18n/sr.json
    - assets/questions/questions_en.json
    - assets/questions/questions_sr.json
